version: '3.8'

services:
  mcp-fal-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FAL_KEY=${FAL_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
